### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by HexwellC** [foxcpp/Hexicord#1]
- [x]  Websockets and REST wrappers
- [x]  Reuse of connections
- [x]  Discord Client core
- [x]  REST methods and all the nice things
- [x]  Documentation.
- [x]  Reconnect if disconnected unexpectedly.
- [x]  RAII! MORE RAII!!!!!11111!!!!1
